version: '3'
services:
  nginx-certbot:
    container_name: nginx-certbot
    env_file: .env
    image: rabbotio/nginx-certbot
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/ssl:/etc/ssl
      - /var/www:/var/www
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/letsencrypt:/var/log/letsencrypt
    depends_on:
      - nginx
      - certbot
    links:
      - nginx
      - certbot
    networks:
      - back
    command:
      - . /usr/local/bin/dhparam.sh
      - . /usr/local/bin/new.sh

  nginx:
    image: nginx:alpine
    container_name: nginx
    env_file: .env
    restart: on-failure
    networks:
      - back
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/ssl:/etc/ssl
      - /var/www:/var/www
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    env_file: .env
    environment:
      - DOMAIN=$DOMAIN
      - CERTBOT_EMAIL=$CERTBOT_EMAIL
      - ACME_WWWROOT=${ACME_WWWROOT:-/usr/share/nginx/html}
    networks:
      - back
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/letsencrypt:/var/log/letsencrypt

networks:
  back:
