version: '3'
services:
  nginx:
    image: rabbotio/nginx-certbot
    container_name: nginx
    env_file: .env
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - "80:80"
      - "443:443"